package com.learning.core.listeners;

import static com.learning.core.constants.ThumbnailNodeMovedListenerConstants.ASSET_UPDATE_PATH;
import static com.learning.core.constants.ThumbnailNodeMovedListenerConstants.JCR_PATH;
import static com.learning.core.constants.ThumbnailNodeMovedListenerConstants.THUMBNAIL_WORKFLOW_PATH;
import static com.learning.core.constants.ThumbnailNodeMovedListenerConstants.ORIGINAL_RENDITION_RELATIVE_PATH;
import static com.learning.core.constants.ExceptionConstants.ERROR_EXEC_WORKFLOW;
import static com.learning.core.constants.ExceptionConstants.ERROR_LOGIN;
import static com.learning.core.constants.ExceptionConstants.ERROR_REPOSITORY;

import javax.jcr.RepositoryException;
import javax.jcr.Session;
import javax.jcr.Workspace;
import javax.jcr.observation.Event;
import javax.jcr.observation.EventIterator;
import javax.jcr.observation.EventListener;
import javax.jcr.observation.ObservationManager;


import org.apache.sling.api.resource.LoginException;
import org.apache.sling.api.resource.ResourceResolver;
import org.apache.sling.api.resource.ResourceResolverFactory;
import org.osgi.service.component.ComponentContext;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.day.cq.workflow.WorkflowException;
import com.day.cq.workflow.WorkflowService;
import com.day.cq.workflow.WorkflowSession;
import com.day.cq.workflow.exec.WorkflowData;
import com.day.cq.workflow.model.WorkflowModel;
import com.learning.core.utility.ResourceResolverUtil;

/**
 * Adds an event listener to run the ArgilDX Watermark Workflow on node move
 * under '/content/dam/movedimages'
 * 
 * @author ArgilDX
 */
@Component(service=EventListener.class,immediate=true)
public class ThumbnailNodeMovedListener implements EventListener {
	
	

	/**
	 * The Logger
	 */
	Logger log = LoggerFactory.getLogger(ThumbnailNodeMovedListener.class);

	/**
	 * For invoking the Workflow
	 */
	@Reference
	WorkflowService workflowService;

	/**
	 * The Resource Resolver Factory Service
	 */
	@Reference
	ResourceResolverFactory resourceResolverFactory;

	/**
	 * The Resource Resolver object
	 */
	ResourceResolver resolver;

	/**
	 * The session object
	 */
	Session session;
	/**
	 * Method run on component activation. Executed once in the component's life
	 * cycle.
	 * 
	 * @param ctx
	 *            The component context object
	 */
	@Activate
	protected void activate(ComponentContext ctx) {
		try {

			// Take session. The event listener uses this session to execute its logic. NB: This
			// is only for demonstrative purposes. 
			try {
				resolver=ResourceResolverUtil.newResolver(resourceResolverFactory);
			} catch (LoginException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			session =resolver.adaptTo(Session.class);

			if (session == null) {
				return;
			}

			// The workspace is used to get the ObservationManager
			Workspace workspace = session.getWorkspace();

			if (workspace == null) {
				return;
			}

			// The ObservationManager allows us to add and remove Event Listeners
			ObservationManager observationManager = workspace.getObservationManager();

			// Building the parameters for adding the event listener

			// Whether the subfolders of the given path should also be watched
			boolean isDeep = true;

			// Only events whose associated node has one of the UUIDs in this list will be
			// received. If this parameter is null then no UUID-related restriction is
			// placed on events received.
			String[] uuid = null;

			// Only events whose associated node has one of the node types (or a subtype of
			// one of the node types) in this list will be received. If this parameter is
			// null then no node type-related restriction is placed on events received.
			String[] nodeTypeName = null;

			// If noLocal is true, then events generated by the session through which the
			// listener was registered are ignored. Otherwise, they are not ignored.
			boolean noLocal = true;

			// Registering the event listener
			observationManager.addEventListener(this, Event.NODE_MOVED, ASSET_UPDATE_PATH, isDeep, uuid, nodeTypeName,
					noLocal);

		} catch (javax.jcr.LoginException lEx) {
			log.error(ERROR_LOGIN + lEx.getMessage(), lEx);
		} catch (RepositoryException rEx) {
			log.error(ERROR_REPOSITORY + rEx.getMessage(), rEx);
		}
	}

	/**
	 * Method run on component deactivation. Executed once in the component's life
	 * cycle.
	 * 
	 * @param componentContext
	 *            The component context
	 * @throws RepositoryException
	 */
	@Deactivate
	protected void deactivate(ComponentContext componentContext) throws RepositoryException {

		try {
			if (session == null) {
				return;
			}

			// The workspace is used to get the ObservationManager
			Workspace workspace = session.getWorkspace();

			if (workspace == null) {
				return;
			}

			// The ObservationManager allows us to add and remove Event Listeners
			ObservationManager observationManager = workspace.getObservationManager();

			if (observationManager != null) {
				observationManager.removeEventListener(this);
			}
		} finally {
			if (session != null) {
				session.logout();
				session = null;
			}
		}
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void onEvent(EventIterator itr) {
		while (itr.hasNext()) {
			Event currentEvent = itr.nextEvent();
			try {
				// This is only for demonstrative purposes. In a project, use a service resource
				// resolver
				

				// Invoke the adaptTo method to create a Session
				Session localSession = resolver.adaptTo(Session.class);

				if (localSession == null) {
					return;
				}

				// Create a workflow session
				WorkflowSession wfSession = workflowService.getWorkflowSession(localSession);

				// Get the workflow model
				WorkflowModel wfModel = wfSession.getModel(THUMBNAIL_WORKFLOW_PATH);

				// Get the Workflow data. The first parameter in the newWorkflowData method is
				// the payloadType. Just a fancy name to let it know what type of workflow it is
				// working with.
				WorkflowData wfData = wfSession.newWorkflowData(JCR_PATH, currentEvent.getPath()+ORIGINAL_RENDITION_RELATIVE_PATH);

				// Start the Workflow.
				wfSession.startWorkflow(wfModel, wfData);

			} catch (WorkflowException wEx) {
				log.error(ERROR_EXEC_WORKFLOW + wEx.getMessage(), wEx);
			} catch (RepositoryException rEx) {
				log.error(ERROR_REPOSITORY + rEx.getMessage(), rEx);
			} finally {
				if (resolver != null) {
					resolver.close();
					resolver = null;
				}
			}
		}
	}
}
